In [ ]:
import pandas as pd

raw_data = pd.DataFrame({
        'bioguideId': ['A1', 'B2', 'C3'],
        'name': ['Edgar', 'Pedro', 'Alfonso'],
        'partyName': ['Democratic', 'Republican', 'Democratic'],
        'state': ['CA', 'TX', 'ny']
    })

In [3]:
raw_data.head()

  bioguideId     name   partyName state
0         A1    Edgar  Democratic    CA
1         B2    Pedro  Republican    TX
2         C3  Alfonso  Democratic    ny

In [7]:
silver_df = raw_data.copy()

silver_df = silver_df[silver_df['partyName'] == 'Democratic']
silver_df['state'] = silver_df['state'].str.lower()

silver_df.head()

  bioguideId     name   partyName state
0         A1    Edgar  Democratic    ca
2         C3  Alfonso  Democratic    ny

In [ ]:
silver_df.loc[2, 'state'] == 'ny'

True

In [29]:
df = silver_df.copy()
# ✅ CORRECTO - Crea un array de True/False
filtro = df['partyName'] == 'Democratic'
# filtro es: [True, False, True]

# df.loc[filtro]  # Funciona porque es booleano
print(type(filtro))

<class 'pandas.Series'>

In [ ]:
print(df['partyName'] == 'Democratic')

In [32]:
silver_df.iloc[1, 'state'] == 'ny'

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types